context("compare.fits works")
set.seed(12323)
options(warn = -1)
test_that("compare_fits works with linear models", {
  full      = lm(y~a*x, data=small)
  reduced   = lm(y~a+x, data=small)
  lots_pred1= lm(y~a + b + z + x, data=small)
  lots_pred2= lm(y~a + b + z * x, data=small)
  plyn      = lm(y_poly~ a + x + I(x^2), data=small)
  plyn_red  = lm(y_poly~ a + x, data=small)
  full_miss = lm(y~a+x_miss, data=small)
  red_miss  = lm(y~a, data=small)
  vdiffr::expect_doppelganger("compare_fits without model/formula", compare.fits(model1=full, model2=reduced))
  vdiffr::expect_doppelganger("compare_fits with ghostline", compare.fits(model1=full, model2=reduced, ghost.line="black"))
  vdiffr::expect_doppelganger("compare_fits with fewer quadriture points", compare.fits(model1=full, model2=reduced, num_points = 6))
  vdiffr::expect_doppelganger("compare_fits without model2", compare.fits(model1=full))
  vdiffr::expect_doppelganger("compare_fits without predictors", compare.fits(model1=lm(y~1, data=small)))
  vdiffr::expect_doppelganger("compare_fits with lots of predictors", compare.fits(model1=lots_pred1, model2=lots_pred2))
  vdiffr::expect_doppelganger("compare_fits with polynomial", compare.fits(y_poly~x | a, data=small, model1=plyn, model2=plyn_red))
  vdiffr::expect_doppelganger("compare_fits with missing data in one", compare.fits(y~x_miss | a, data=small, model1=full_miss, model2=red_miss))
})

test_that("compare_fits works with other models", {
  poly_full = MASS::polr(w_a~a * x, data=small %>% mutate(w_a = factor(w_a)))
  poly_red  = MASS::polr(w_a~a + x, data=small%>% mutate(w_a = factor(w_a)))
  rf_mod    = randomForest::randomForest(y~a + b + z, data=small)
  rf_cfor   = party::cforest(y~a + b + z, data=small)
  mixed_full=lme4::lmer(y~x + a + (x | id), data=small_mixed)
  mixed_red =lme4::lmer(y~x + a + (1 | id), data=small_mixed)
  vdiffr::expect_doppelganger("compare_fits with rlm", compare.fits(model1 = MASS::rlm(y~a + x, data=small), model2 =  lm(y~a*x, data=small)))
  vdiffr::expect_doppelganger("compare_fits with rf", compare.fits(y~z | a + b, model1 = rf_mod, model2 = rf_cfor))
  vdiffr::expect_doppelganger("compare_fits with glms", compare.fits(model1 = glm(y_bin~x, data=small, family=binomial), model2 = glm(y_bin~x*a, data=small, family=binomial)))
  # compare.fits(model1=mixed_full, model2 = mixed_red, re=TRUE)
  # compare.fits(model1=mixed_full, re=FALSE)  
  # compare.fits(formula = y~x | a + id, model1=mixed_full, re=TRUE)  
  # visualize(mixed_full, plot="model")
})
options(warn = 0)