
# This file is automatically generated, you probably don't want to edit this

flexplotaOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "flexplotaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            out = NULL,
            preds = NULL,
            given = NULL,
            se = TRUE,
            line = "Loess",
            ghost = TRUE,
            resid = FALSE,
            center = "Median + quartiles",
            alpha = 50, ...) {

            super$initialize(
                package='flexplot',
                name='flexplota',
                requiresData=TRUE,
                ...)

            private$..out <- jmvcore::OptionVariable$new(
                "out",
                out)
            private$..preds <- jmvcore::OptionVariables$new(
                "preds",
                preds)
            private$..given <- jmvcore::OptionVariables$new(
                "given",
                given)
            private$..se <- jmvcore::OptionBool$new(
                "se",
                se,
                default=TRUE)
            private$..line <- jmvcore::OptionList$new(
                "line",
                line,
                options=list(
                    "Loess",
                    "Regression",
                    "Logistic"),
                default="Loess")
            private$..ghost <- jmvcore::OptionBool$new(
                "ghost",
                ghost,
                default=TRUE)
            private$..resid <- jmvcore::OptionBool$new(
                "resid",
                resid,
                default=FALSE)
            private$..center <- jmvcore::OptionList$new(
                "center",
                center,
                options=list(
                    "Median + quartiles",
                    "Mean + sterr",
                    "Mean + stdev"),
                default="Median + quartiles")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                max=100,
                default=50)

            self$.addOption(private$..out)
            self$.addOption(private$..preds)
            self$.addOption(private$..given)
            self$.addOption(private$..se)
            self$.addOption(private$..line)
            self$.addOption(private$..ghost)
            self$.addOption(private$..resid)
            self$.addOption(private$..center)
            self$.addOption(private$..alpha)
        }),
    active = list(
        out = function() private$..out$value,
        preds = function() private$..preds$value,
        given = function() private$..given$value,
        se = function() private$..se$value,
        line = function() private$..line$value,
        ghost = function() private$..ghost$value,
        resid = function() private$..resid$value,
        center = function() private$..center$value,
        alpha = function() private$..alpha$value),
    private = list(
        ..out = NA,
        ..preds = NA,
        ..given = NA,
        ..se = NA,
        ..line = NA,
        ..ghost = NA,
        ..resid = NA,
        ..center = NA,
        ..alpha = NA)
)

flexplotaResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Flexplot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Analysis Plot",
                width=600,
                height=400,
                renderFun=".plot"))}))

flexplotaBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "flexplotaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'flexplot',
                name = 'flexplota',
                version = c(1,0,0),
                options = options,
                results = flexplotaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Flexplot
#'
#' 
#' @param data .
#' @param out .
#' @param preds .
#' @param given .
#' @param se .
#' @param line .
#' @param ghost .
#' @param resid .
#' @param center .
#' @param alpha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
flexplota <- function(
    data,
    out,
    preds,
    given,
    se = TRUE,
    line = "Loess",
    ghost = TRUE,
    resid = FALSE,
    center = "Median + quartiles",
    alpha = 50) {

    if ( ! requireNamespace('jmvcore'))
        stop('flexplota requires jmvcore to be installed (restart may be required)')

    if ( ! missing(out)) out <- jmvcore::resolveQuo(jmvcore::enquo(out))
    if ( ! missing(preds)) preds <- jmvcore::resolveQuo(jmvcore::enquo(preds))
    if ( ! missing(given)) given <- jmvcore::resolveQuo(jmvcore::enquo(given))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(out), out, NULL),
            `if`( ! missing(preds), preds, NULL),
            `if`( ! missing(given), given, NULL))


    options <- flexplotaOptions$new(
        out = out,
        preds = preds,
        given = given,
        se = se,
        line = line,
        ghost = ghost,
        resid = resid,
        center = center,
        alpha = alpha)

    results <- flexplotaResults$new(
        options = options)

    analysis <- flexplotaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
