
# This file is automatically generated, you probably don't want to edit this

modelcompOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "modelcompOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            pred = NULL,
            pred2 = NULL, ...) {

            super$initialize(
                package='glinmod',
                name='modelcomp',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..pred <- jmvcore::OptionVariables$new(
                "pred",
                pred)
            private$..pred2 <- jmvcore::OptionVariables$new(
                "pred2",
                pred2)

            self$.addOption(private$..dep)
            self$.addOption(private$..pred)
            self$.addOption(private$..pred2)
        }),
    active = list(
        dep = function() private$..dep$value,
        pred = function() private$..pred$value,
        pred2 = function() private$..pred2$value),
    private = list(
        ..dep = NA,
        ..pred = NA,
        ..pred2 = NA)
)

modelcompResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Model Comparison")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model Comparison"))}))

modelcompBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "modelcompBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'glinmod',
                name = 'modelcomp',
                version = c(1,0,0),
                options = options,
                results = modelcompResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Model Comparison
#'
#' 
#' @param data .
#' @param dep .
#' @param pred .
#' @param pred2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
modelcomp <- function(
    data,
    dep,
    pred,
    pred2) {

    if ( ! requireNamespace('jmvcore'))
        stop('modelcomp requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(pred)) pred <- jmvcore::resolveQuo(jmvcore::enquo(pred))
    if ( ! missing(pred2)) pred2 <- jmvcore::resolveQuo(jmvcore::enquo(pred2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(pred), pred, NULL),
            `if`( ! missing(pred2), pred2, NULL))


    options <- modelcompOptions$new(
        dep = dep,
        pred = pred,
        pred2 = pred2)

    results <- modelcompResults$new(
        options = options)

    analysis <- modelcompClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
